### PR TITLE
Release/0.3.0

### PR DESCRIPTION
**Pull request by chuwy**

### CODE REVIEW

**Comment by chuwy** [comment]
This is ready for review and publish, except #31 and #32.

**Comment by chuwy** [comment]
Please, also review [this one](https://github.com/snowplow/snowplow-scala-tracker/pull/36/commits/9fea48e63cd1118627664d6ce9c26efa1b58c2dd). It seems we have implemented true timestamp only in Ruby tracker, so I was little bit on hazy on it. I tried to leave it backward-compatible and implement without tracker mutation. It does not require any additional imports.

**Comment by alexanderdean** [comment]
@chuwy - sorry for the delay in reviewing this. It all looks good - just one change: can we rename the `DeviceTimestamp` side of the ADT to `DeviceCreatedTimestamp`? This is for consistency with the [Snowplow Tracker Protocol](https://github.com/snowplow/snowplow/wiki/snowplow-tracker-protocol#12-date--time-parameter).

**Comment by chuwy** [comment]
Sure.

**Comment by chuwy** [comment]
@alexanderdean done.

**Comment by alexanderdean** [comment]
Thanks @chuwy! How is the blog post coming along?

**Comment by chuwy** [comment]
@alexanderdean sorry, I thought I created PR.

**Comment by alexanderdean** [comment]
It's been merged @chuwy! Please can you do a couple of things on Monday:
1. Update the setup guide on wiki given the new Maven Central availability
2. Replace the trackUnstructEvent section in the tech documentation with trackSelfDescribingEvent
3. Post a new post to Discourse with the release

**Comment by alexanderdean** [comment]
And @ninjabear can you delete any branches you were using for CI/CD testing that you don't need any more...

**Pull request merged**
