### PR TITLE
snowplow scala tracker with akka stream/http

### PR DESCRIPTION
**Pull request by ferrlin**
*Integration test is implemented but testing is not completed.
*akka routing not implemented yet
*redis emitter not implemented yet

The tests are fairly comprehensive.

### CODE REVIEW

**Comment by fblundun** [comment]
Thanks @ferrlin ! I've scheduled this for the next version. Do you know what's causing the tests to sometimes fail in Travis CI?

**Comment by ferrlin** [comment]
updated the code to pass all test.

**Comment by alexanderdean** [comment]
Pushing back...

**Comment by chuwy** [comment]
Closing PR. Unfortunately it is too far away from our current state and vision of the tracker.

**Pull request closed without merging**
