### PR TITLE
Tracking errors

### PR DESCRIPTION
**Pull request by aparra**
This PR adds an error handler for Tracker. More details in this ticket #47

### CODE REVIEW

**Comment by aparra** [comment]
@chuwy do I need take care about this conflict or you will figure out?

**Comment by chuwy** [comment]
Hey @aparra, no, no worries. This already has been cherry-picked into https://github.com/snowplow/snowplow-scala-tracker/pull/64 and should be available on Maven Central as 0.5.0-M3 very soon. I'll close this PR when QA will confirm everything works.

**Comment by snowplowcla** [comment]
@aparra has signed the Software Grant and Corporate Contributor License Agreement

**Comment by chuwy** [comment]
Cherry-picked into https://github.com/snowplow/snowplow-scala-tracker/pull/64. Thank you very much.

**Pull request closed without merging**
