### PR TITLE
Add support for missing ecommerce related events.

### PR DESCRIPTION
**Pull request by christoph-buente**
* trackAddToCart
* trackRemoveFromCart
* trackTransaction
* trackTransactionItem

### CODE REVIEW

**Review by chuwy — APPROVED** [review]
Looks good! Thanks @christoph-buente!

**Comment by snowplowcla** [comment]
@christoph-buente has signed the Software Grant and Corporate Contributor License Agreement. Thanks so much

**Comment by christoph-buente** [comment]
Great! Any plans for a specific milestone?

**Comment by alexanderdean** [comment]
Scheduled! What's your use case for it @christoph-buente?

**Comment by chuwy** [comment]
Cherry-picked into https://github.com/snowplow/snowplow-scala-tracker/pull/64. Thank you very much.

**Pull request closed without merging**
