### PR TITLE
Release 1.0.1

### PR DESCRIPTION
**Pull request by andreamarcolin**
Quite a few things in there, but mostly sbt/scala/plugins/dependencies bumps. 
Also switched publishing from Bintray to GitHub and added MiMa, see commits for a more detailed list.

Waiting for iglu-scala-core 1.0.1 to be published before marking this as ready for review

### CODE REVIEW

**Comment by andreamarcolin** [comment]
@paulboocock this might need GH secrets for Sonatype publishing (just like iglu-scala-core), I'm not sure whether they are already set or not

**Review by istreeter — APPROVED** [review]
Looks great

**Comment by paulboocock** [comment]
Some of the secrets were in place, but the PGP ones were missing so I've added them and we should be good to go.

**Comment by andreamarcolin** [comment]
@paulboocock do you think there's anything missing here or can we merge and cut out a release?

**Comment by paulboocock** [comment]
I think we're all good, we just got blocked by annual leave and such. I'll try and find the time to cut a release this week.

**Pull request merged**
